### ISSUE TITLE
Improve the game

### ISSUE THREAD

**Issue by nasivuela** [Adalab/e-s2-evaluacion-intermedia-desigc#1]
Awesome job @desigc  !!!

Here you have some tips to improve the exercise:

- [x] Remove unused files/folders from the project: assets/icons, assets/images...
- [x] Add a form tag on HTML to send the form when hitting the enter key
- [x] Extract the feedback painter to a function
- [x] It seems like you are printing 'undefined' word on HTML when the number is too high!
- [x] Move variables and constants declarations to the top of the file
- [x] Indent and avoid extra white spaces to improve readability and avoid bugs
- [x] Remove commented code

Let me know if you have any doubts ;)

Go for it!!

**Comment by desigc** [comment]
Hi @nasivuela !! 
Thanks so much for your feedback and sorry for the delay. I've modified all your corrections.

**Comment by nasivuela** [comment]
Well done @desigc !!

![](https://media.giphy.com/media/100QWMdxQJzQC4/200w_d.gif)
